### ISSUE TITLE
Work with refs?

### ISSUE THREAD

**Issue by switz** [tanvesh01/motion-hooks#4]
Cool lib! Could this be accomplished?

```
const { play, isFinished, replay, ref } = useMotionAnimate(
    { y: -20, opacity: 1 },
    {
      delay: stagger(0.3),
      duration: 0.5,
      easing: [0.22, 0.03, 0.26, 1],
    },
  );

return (
  <div ref={ref} />
);
```

Or even: `useMotionAnimate(ref.current, deltas, opts)` where ref is a useRef.

**Comment by tanvesh01** [comment]
Hey, @switz Thanks! Yup that works! Have a look at this example, you just have to pass `ref`.
```jsx
 const listItemRef = React.useRef(null);
 const { play: playListAnimation } = useMotionAnimate(
        listItemRef,
        { y: -20, opacity: 1 },
        { duration: 2 }
    );

useEffect(() => {
        playListAnimation();
}, []);

return  <div className="listItem" ref={listItemRef}>
                List item box
            </div>
```
my bad should have added this to docs, will do that :)

**Comment by tanvesh01** [comment]
Hey, I am going to close this one. Have added a ref example in README.md.

[README](https://github.com/tanvesh01/motion-hooks/blob/main/README.md)
